export const initialVendors = [
    {
        vendorId: '100001',
        name: 'Siemens AG',
        country: 'DE',
        city: 'Munich',
        accountGroup: 'LIEF',
        paymentTerms: 'Z030',
        ytdSpend: 180400,
        onTime: 97,
        rating: 'A+',
    },
    {
        vendorId: '100002',
        name: 'BASF SE',
        country: 'DE',
        city: 'Ludwigshafen',
        accountGroup: 'LIEF',
        paymentTerms: 'Z060',
        ytdSpend: 95200,
        onTime: 88,
        rating: 'A',
    },
    {
        vendorId: '100003',
        name: 'Bosch GmbH',
        country: 'DE',
        city: 'Stuttgart',
        accountGroup: 'LIEF',
        paymentTerms: 'Z030',
        ytdSpend: 44100,
        onTime: 91,
        rating: 'A',
    },
    {
        vendorId: '100004',
        name: '3M Deutschland GmbH',
        country: 'DE',
        city: 'Neuss',
        accountGroup: 'LIEF',
        paymentTerms: 'Z045',
        ytdSpend: 21800,
        onTime: 79,
        rating: 'B',
    },
    {
        vendorId: '100005',
        name: 'ABB Ltd',
        country: 'CH',
        city: 'Zurich',
        accountGroup: 'LIEF',
        paymentTerms: 'Z030',
        ytdSpend: 310000,
        onTime: 94,
        rating: 'A+',
    },
    {
        vendorId: '100006',
        name: 'Henkel AG',
        country: 'DE',
        city: 'Düsseldorf',
        accountGroup: 'LIEF',
        paymentTerms: 'Z030',
        ytdSpend: 12400,
        onTime: 100,
        rating: 'A+',
    },
    {
        vendorId: '100007',
        name: 'Linde AG',
        country: 'DE',
        city: 'Munich',
        accountGroup: 'LIEF',
        paymentTerms: 'Z030',
        ytdSpend: 67200,
        onTime: 85,
        rating: 'A',
    },
    {
        vendorId: '100008',
        name: 'Thyssen Krupp AG',
        country: 'DE',
        city: 'Essen',
        accountGroup: 'LIEF',
        paymentTerms: 'Z060',
        ytdSpend: 8900,
        onTime: 62,
        rating: 'C',
    },
];

export const initialPOs = [
    {
        poNumber: '4500001234',
        documentType: 'NB',
        vendorId: '100001',
        vendorName: 'Siemens AG',
        materialGroup: 'Electrical',
        plant: '1000',
        currency: 'EUR',
        netValue: 42500,
        deliveryDate: '2026-06-28',
        status: 'Approved',
        grProgress: 100,
        grStatus: 'Full',
        buyer: 'H. Missaoui',
        items: [
            {
                item: '10',
                material: 'MAT-78231',
                description: 'Industrial Motor 7.5kW IE3',
                plant: '1000',
                qty: 10,
                uom: 'EA',
                netPrice: 4000,
                netValue: 40000,
                deliveryDate: '2026-06-28',
                grStatus: 'GR Done',
            },
            {
                item: '20',
                material: 'MAT-78232',
                description: 'Motor Control Cable 4x2.5mm²',
                plant: '1000',
                qty: 50,
                uom: 'M',
                netPrice: 50,
                netValue: 2500,
                deliveryDate: '2026-06-28',
                grStatus: 'GR Done',
            },
        ],
        createdBy: 'H.MISSAOUI',
        createdOn: '2026-06-10',
        changedOn: '2026-06-12',
        paymentTerms: 'Z030',
        taxCode: 'V1',
        incoterms: 'DAP',
        companyCode: 'DE01',
        purchaseOrg: '1000',
        purchaseGroup: '001',
        itemCategory: 'Standard',
        history: [
            {
                date: '2026-06-10',
                time: '09:12',
                user: 'H.MISSAOUI',
                action: 'PO Created',
                document: '4500001234',
                amount: 42500,
            },
            {
                date: '2026-06-10',
                time: '11:30',
                user: 'SYSTEM',
                action: 'Sent for approval (L1)',
                document: '—',
                amount: null,
            },
            {
                date: '2026-06-11',
                time: '08:55',
                user: 'K.SCHMIDT',
                action: 'Approved (L1)',
                document: '—',
                amount: null,
            },
            {
                date: '2026-06-12',
                time: '14:20',
                user: 'M.HOFFMAN',
                action: 'Approved (L2) — Released',
                document: '—',
                amount: null,
            },
            {
                date: '2026-06-14',
                time: '10:45',
                user: 'H.MISSAOUI',
                action: 'Goods Receipt Posted',
                document: '5000000112',
                amount: 42500,
            },
        ],
    },
    {
        poNumber: '4500001235',
        documentType: 'NB',
        vendorId: '100002',
        vendorName: 'BASF SE',
        materialGroup: 'Chemicals',
        plant: '1000',
        currency: 'EUR',
        netValue: 18900,
        deliveryDate: '2026-06-30',
        status: 'Ordered',
        grProgress: 50,
        grStatus: 'Part',
        buyer: 'K. Weber',
        items: [],
    },
    {
        poNumber: '4500001236',
        documentType: 'NB',
        vendorId: '100003',
        vendorName: 'Bosch GmbH',
        materialGroup: 'Mech. Parts',
        plant: '2000',
        currency: 'EUR',
        netValue: 7340,
        deliveryDate: '2026-07-05',
        status: 'Pending',
        grProgress: 0,
        grStatus: 'None',
        buyer: 'H. Missaoui',
        items: [],
    },
    {
        poNumber: '4500001237',
        documentType: 'NB',
        vendorId: '100004',
        vendorName: '3M Deutschland GmbH',
        materialGroup: 'Safety',
        plant: '1000',
        currency: 'EUR',
        netValue: 3200,
        deliveryDate: '2026-07-12',
        status: 'Draft',
        grProgress: 0,
        grStatus: 'None',
        buyer: 'S. Müller',
        items: [],
    },
    {
        poNumber: '4500001238',
        documentType: 'FO',
        vendorId: '100005',
        vendorName: 'ABB Ltd',
        materialGroup: 'Control Systems',
        plant: '3000',
        currency: 'EUR',
        netValue: 91000,
        deliveryDate: '2026-07-20',
        status: 'Approved',
        grProgress: 0,
        grStatus: 'None',
        buyer: 'H. Missaoui',
        items: [],
    },
    {
        poNumber: '4500001239',
        documentType: 'NB',
        vendorId: '100006',
        vendorName: 'Henkel AG',
        materialGroup: 'Chemicals',
        plant: '1000',
        currency: 'EUR',
        netValue: 5600,
        deliveryDate: '2026-07-01',
        status: 'Received',
        grProgress: 100,
        grStatus: 'Full',
        buyer: 'K. Weber',
        items: [],
    },
];

export const dashboardMetrics = {
    openPOs: 47,
    totalSpend: 1240000,
    pendingApproval: 4,
    onTimeDelivery: 91,
    monthlySpend: [120, 140, 160, 130, 150, 180],
    statusBreakdown: [40, 25, 18, 9, 8],
};

export const analyticsData = {
    spendByGroup: [310, 180, 90, 95, 44, 22],
    vendorSpend: [310, 180, 67, 95, 44, 12, 22, 9],
    trend: {
        actual: [380, 420, 510, 480, 530, 510],
        budget: [400, 400, 500, 500, 500, 500],
    },
};
